name: backend_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_cors_headers: ^0.1.5
  uuid: ^4.0.0
  json_annotation: ^4.8.1
  mongo_dart: ^0.10.0


dev_dependencies: 
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

